/*
 * File:    Ex_23_hailstones.c
 * Author:  Alexander130892
 * Date:    25-3-2026
 *
 * Description:
 *   This file implements the Collatz conjecture (hailstone sequence)
 *   starting from the number 114, recursively applying the rules of
 *   dividing by 2 if even or multiplying by 3 and adding 1 if odd
 *   until reaching 1. It prints each number in the sequence and counts
 *   the total steps needed to reach 1.
 */
 //Libraries
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <limits.h>

//Consts
#define STOP 17
#define FOREVER 1

//Typedefs

//Prototypes
void hailstones(int n);

int main(){
    int n=114;
    printf("Hailstones generated by %d:\n  %d  ",n,n);
    hailstones(n);
    return 0;
}

void hailstones(int n){
    static int cnt=0;
    if(n==1){
        cnt++;
        printf("\nNeeded %d steps to reach 1\n", cnt);
        return;
    }
    if(n%2==0){
        printf("%d  ", n/2);
        cnt++;
        hailstones(n/2);
    }else{
        printf("%d  ", 3*n+1);
        cnt++;
        hailstones(3*n+1);
    }
}