/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "stm32f446re.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "timers.h"

#include "timer.h"
#include "uart.h"
#include "i2c.h"
#include "spi.h"
#include "mpu6050.h"
#include "bmp280.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define WAKE_UP_DELAY		10000
#define HEARTBEAT_PERIOD	5000
#define BMP280_PERIOD		1000
#define STR_LEN 			64
#define N_TASKS 			10	//Oversized

QueueHandle_t xQueue_bmp280;
QueueHandle_t xQueue_mpu6050;
QueueHandle_t xQueueUARTRx;

SemaphoreHandle_t xMutexUart;

TimerHandle_t xTimerBMP280;
TimerHandle_t xTimerHeartBeat;

TaskHandle_t xSPITaskHandle;		// BMP280 @ 1 Hz (SW Timer)
TaskHandle_t xI2CTaskHandle;		// MPU6050 @ 100 Hz (HW TIM2)
TaskHandle_t xCmdTaskHandle;		// UART Command Parsing
TaskHandle_t xLogTaskHandle;		// CSV over UART + Watchdog kick (SW Timer)

TaskStatus_t pxTaskStatusArray[N_TASKS];

void vApplicationTickHook(void){}
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){
	uart_send_string("Stack Overflow detected! Task: ");
	uart_send_string(pcTaskName);
	uart_send_string("\r\n");

	taskDISABLE_INTERRUPTS();
	//Spin loop - infinite loop to be caught by debugger
	for(;;);
}
void vApplicationIdleHook(void){}
void vApplicationMallocFailedHook(void){}

void vSPITask(void *pvParameters);
void vI2CTask(void *pvParameters);
void vCmdTask(void *pvParameters);
void vLogTask(void *pvParameters);

void vBMP280Timer 		(TimerHandle_t xTimerBMP280  );
void vHeartBeatTimer 	(TimerHandle_t xTimerHeartBeat );
volatile bool b_timeout_mpu6050 = false;
volatile bool b_timeout_bmp280 = false;

int main(void)
{
// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)CPACR) |= ((3UL << 10*2) | (3UL << 11*2));
// UART
	uart_gpio_init();
	uart_init();
////Timer
	timer2_init(); // starts of disabled
//MPU6050
	i2c_init_gpio();
	i2c_init();
	uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
	mpu6050_init(mpu_addr);
//BMP280
	spi_gpio_init();
	bmp280_spi_gpio_init();
	spi_init();
	bmp280_spi_init();
// Settling delay
	for(volatile int i = 0; i < WAKE_UP_DELAY; i++);

//-- Kernel Object ---
	xQueue_mpu6050 		= xQueueCreate( 5, sizeof(mpu6050_data_t));
	xQueue_bmp280 		= xQueueCreate( 5, sizeof(int32_t));
	xQueueUARTRx 		= xQueueCreate( 20, sizeof(char));
	xMutexUart 			= xSemaphoreCreateMutex();

//--- Tasks	----
	xTaskCreate(vSPITask,				// Task function
				"SPI - BMP280 Task",				// Task name
				128,							// Stack Size
				NULL,		// Parameters to function
				1,								// Priority
				&xSPITaskHandle);			// Handle for task
	xTaskCreate(vI2CTask,	"I2C - MPU6050 Task",	128, (void*)(uintptr_t)mpu_addr, 1,	&xI2CTaskHandle);
	xTaskCreate(vCmdTask,	"Command Parser Task", 128, NULL, 1,	&xCmdTaskHandle);
	xTaskCreate(vLogTask,	"CSV + UART Task", 256, NULL, 1,	&xLogTaskHandle);

//--- Timer	 ----
	xTimerBMP280 = xTimerCreate( "BMP280 Timer",		// Name
								BMP280_PERIOD,			// Period
								pdTRUE,					// Auto-reload or not
								(void *) 1,				// ID
								&vBMP280Timer );
	xTimerHeartBeat = xTimerCreate( "Watchdog Timer",	// Name
								HEARTBEAT_PERIOD,		// Period
								pdTRUE,					// Auto-reload or not
								(void *) 1,				// ID
								&vHeartBeatTimer );
	if(xTimerBMP280 == NULL || xTimerHeartBeat == NULL ){
			uart_send_string("Failed to start timers!\r\n");
	}
	xTimerStart(xTimerBMP280, 	 0);
	xTimerStart(xTimerHeartBeat, 0);
//-- Scheduler	---
	uart_send_string("Ready to schedule:\r\n");
	vTaskStartScheduler();
    /* Loop forever */

	for(;;);
}
void vSPITask(void *pvParameters){
	int32_t data;
	xSemaphoreTake(xMutexUart, portMAX_DELAY);
	uart_send_string("vSPI_Task running\r\n");
	xSemaphoreGive(xMutexUart);
	for(;;){
		if(ulTaskNotifyTake(pdTRUE,portMAX_DELAY)){
			if(bmp280_spi_read_temp(&data) == STATUS_OK){
				b_timeout_bmp280 = false;
				xQueueSend( xQueue_bmp280, 	(void *) &data, 0);
			}else{
				vTaskDelay(pdMS_TO_TICKS(10)); // yield before retrying// likely wrong read
			}
		}
	}
}
void vI2CTask(void *pvParameters){
	uint8_t dev_addr = (uint8_t)(uintptr_t)pvParameters;
	mpu6050_data_t data;
	//	Start-up TIM2
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		|= (0x1 << 0);
	xSemaphoreTake(xMutexUart, portMAX_DELAY);
	uart_send_string("vI2C_Task running\r\n");
	xSemaphoreGive(xMutexUart);
	for(;;){
		if(ulTaskNotifyTake(pdTRUE,portMAX_DELAY)){
			if(mpu6050_read_data(dev_addr, &data)==STATUS_OK){
				b_timeout_mpu6050 = false;
				xQueueSend( xQueue_mpu6050, 	(void *) &data, 0);
			}else{
				vTaskDelay(pdMS_TO_TICKS(10)); // yield before retrying// likely wrong read
			}
		}
	}
}
void vLogTask(void *pvParameters){
	mpu6050_data_t mpu6050_read;
	int32_t	bmp280_read;
	char output_str[STR_LEN];
	xSemaphoreTake(xMutexUart, portMAX_DELAY);
	uart_send_string("vLog_Task running\r\n");
	xSemaphoreGive(xMutexUart);
	for(;;){
		if(ulTaskNotifyTake(pdTRUE,0)){
			if(b_timeout_mpu6050){
				xSemaphoreTake(xMutexUart, portMAX_DELAY);
				uart_send_string("ERROR: MPU6050 Not responding!\r\n");
				xSemaphoreGive(xMutexUart);
			}else if (b_timeout_bmp280){
				xSemaphoreTake(xMutexUart, portMAX_DELAY);
				uart_send_string("ERROR: BMP280 Not responding!\r\n");
				xSemaphoreGive(xMutexUart);
			}
		}
		if(xQueueReceive(	xQueue_mpu6050, 	(void *) &mpu6050_read, pdMS_TO_TICKS(50)) == pdTRUE){
			snprintf(output_str, sizeof(output_str),
							"%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\r\n",
							(float)mpu6050_read.accel_x/16384,	(float)mpu6050_read.accel_y/16384,	(float)mpu6050_read.accel_z/16384, 		//2^15 / 2g (sensitivity)
							(float)mpu6050_read.gyro_x/131,		(float)mpu6050_read.gyro_y/131,		(float)mpu6050_read.gyro_z/131			//2^15 / 250g (sensitivity)
							);
			xSemaphoreTake(xMutexUart, portMAX_DELAY);
			uart_send_string(output_str);
			xSemaphoreGive(xMutexUart);
		}
		if(xQueueReceive(	xQueue_bmp280, 	(void *) &bmp280_read, 0) == pdTRUE){
			snprintf(output_str, sizeof(output_str), "%ld.%02ld\r\n",bmp280_read/100, bmp280_read%100);
			xSemaphoreTake(xMutexUart, portMAX_DELAY);
			uart_send_string(output_str);
			xSemaphoreGive(xMutexUart);
		}
	}
}
void vCmdTask(void *pvParameters ){
	char item;
	char command[20];
	char* arg;
	char* cmd;
	uint8_t index = 0;
	xSemaphoreTake(xMutexUart, portMAX_DELAY);
	uart_send_string("vCmd_Task running\r\n");
	xSemaphoreGive(xMutexUart);
	for(;;){
		if(xQueueReceive(	xQueueUARTRx, 	(void *) &item, 100) == pdTRUE){
			if(item == '\r'){
				// command finished
				command[index]='\0';
				xSemaphoreTake(xMutexUart, portMAX_DELAY);
				uart_send_string(command);
				uart_send_string("\r\n");
				xSemaphoreGive(xMutexUart);

				cmd = strtok(command, " ");
				if(strcmp(cmd, "log") == 0){
					arg = strtok(NULL, " "); // argument
					if(arg==NULL){
						;// do nothing
					}else if(strcmp(arg, "on") == 0){
						// Clear both Queues
						xQueueReset(xQueue_bmp280);
						xQueueReset(xQueue_mpu6050);
						//Start logging (both sensors)
						xTimerStart(xTimerBMP280, 0);
						xTimerStart(xTimerHeartBeat, 0);
						b_timeout_bmp280 = false;
						b_timeout_mpu6050 = false;
						// Enable TIM2 (For MPU6050)
						*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		|= (0x1 << 0); // CEN bit at pos 0 > Enable after setting up
					}else if(strcmp(arg, "off") == 0){
						//Stop logging (both sensors)
						xTimerStop(xTimerBMP280, 0);
						xTimerStop(xTimerHeartBeat, 0);
						// Disable TIM2
						*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		&= ~(0x1 << 0); // CEN bit at pos 0 > Enable after setting up
					}else{
						xSemaphoreTake(xMutexUart, portMAX_DELAY);
						uart_send_string("Invalid argument!\r\n");
						xSemaphoreGive(xMutexUart);
					}
				}else if (strcmp(cmd, "hwm")==0){
					UBaseType_t uxCount = uxTaskGetNumberOfTasks();
					uxTaskGetSystemState(pxTaskStatusArray, uxCount, NULL);
					char hwm_str[STR_LEN];
					xSemaphoreTake(xMutexUart, portMAX_DELAY);
					for(uint8_t task_i=0; task_i < uxCount; task_i++){
						uart_send_string("Task: ");
						uart_send_string(pxTaskStatusArray[task_i].pcTaskName);
						uart_send_string(" - HWM Value: ");
						snprintf(hwm_str, sizeof(hwm_str), "%lu\r\n", pxTaskStatusArray[task_i].usStackHighWaterMark);
						uart_send_string(hwm_str);
					}
					xSemaphoreGive(xMutexUart);
				}else if (strcmp(cmd, "mem")==0){
					char heap_str[STR_LEN];
					xSemaphoreTake(xMutexUart, portMAX_DELAY);
					snprintf(heap_str, sizeof(heap_str), "Current free Heap available: %u\r\n", xPortGetFreeHeapSize());
					uart_send_string(heap_str);
					snprintf(heap_str, sizeof(heap_str), "Minimal free Heap Ever available: %u\r\n", xPortGetMinimumEverFreeHeapSize());
					uart_send_string(heap_str);
					xSemaphoreGive(xMutexUart);
				}
				//	reset for next command
				index = 0;
			}else
			{
				command[index] = item;
				index++;
				index = index % 20; // protect against overflow
			}
		}
	}
}
void vHeartBeatTimer( TimerHandle_t xTimerHeartBeat ){
	if(b_timeout_mpu6050){
		xTaskNotifyGive(xLogTaskHandle);			//notify vUARTTask
	}else{
		b_timeout_mpu6050 = true; 		//reset -- sensor should set before next timer-callback
	}
	if(b_timeout_bmp280){
		xTaskNotifyGive(xLogTaskHandle);			//notify vUARTTask
	}else{
		b_timeout_bmp280 = true; 		//reset -- sensor should set before next timer-callback
	}
}
void vBMP280Timer (TimerHandle_t xTimerBMP280 ){
	xTaskNotifyGive(xSPITaskHandle);
}

