/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "FreeRTOS.h"
#include "task.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define DELAY_VALUE	5000

void vApplicationTickHook(void){}
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){}
void vApplicationIdleHook(void){}
void vApplicationMallocFailedHook(void){}

void vLEDTask(void *pvParameters);
void vUARTTask(void *pvParameters);

int main(void)
{
	uart_gpio_init();
	uart_init();
	LED_init();

	xTaskCreate(vLEDTask,						// Task function
				"LED Blink",					// Task name
				configMINIMAL_STACK_SIZE,		// Stack Size
				NULL,							// Parameters to function
				1,								// Priority
				NULL);							// Handle for task
	xTaskCreate(vUARTTask,
				"UART Tick",
				configMINIMAL_STACK_SIZE,
				NULL,
				1,
				NULL);

	vTaskStartScheduler();
		// Timing to be set-up in a later week
    /* Loop forever */
	for(;;);
}


void vLEDTask(void *pvParameters){
	for(;;){
		LED_toggle();
		vTaskDelay(pdMS_TO_TICKS(DELAY_VALUE/10));
	}
}
void vUARTTask(void *pvParameters){

	for(;;){
		uart_send_string("tick\r\n");
		vTaskDelay(pdMS_TO_TICKS(DELAY_VALUE));
	}
}
