/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    29-4-2026
 *
 * Description:
 *   This STM32F446RE microcontroller program generates a PWM signal on
 *   pin PA0 using Timer 2 at 1kHz frequency, with a fade function that
 *   appears to modify the duty cycle over time based on millisecond
 *   timing. The code uses direct register manipulation to configure
 *   clocks, GPIO alternate function mode, and PWM generation without
 *   using HAL libraries.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_clocks(void);

void init_gpio_pa0_pwm(void);
void init_pwm(void);

void TIM2_IRQHandler(void);
uint32_t millis();
void fade(uint32_t* start);

#define MAX_LENGTH 64
#define PSC 159		// 	PSC = 159 --> 16 Mhz / 159+1 		= 100 000 Hz
#define ARR 99		//	ARR = 99 	--> 100 000 / 99+1 		= 1000 Hz
uint32_t g_duty_cycle = 50;
uint32_t g_CCR;
volatile uint32_t static overflow_count=0;


int main(void)
{
	g_CCR = g_duty_cycle/100.0*(ARR+1);
	init_clocks();
	init_gpio_pa0_pwm();
	init_pwm();

	/* Loop forever */
	uint32_t start = millis();
	for(;;)
	{
		fade(&start);
	}
}
void init_clocks(void){
	//Clock init GPIOA/GPIO
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 0x1; //01 for GPIOA
	//Clock init timer
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) 	|= 0x1;
}
void init_gpio_pa0_pwm(void){
	//Configure PA5: MODER = 10 (AF mode), AFRL = 0001 (AF1 → TIM2_CH1)
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	&= ~(0x3 << 2*0);
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	|= 	(0x2 << 2*0);
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET)) 	&= ~(0xF << 4*0);
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET)) 	|= 	(0x1 << 4*0);
}
void init_pwm(void){
	// Init timer
		// 	Tim2 Input Clk = 16 MHz (default) --> APB1 prescaler /1, default
		// 	PSC = 159 --> 16 Mhz / 159+1 		= 100 000 Hz
		//	ARR = 99 	--> 100 000 / 99+1 		= 1000 Hz

	// DIR bit at pos 4 > 0 is counting up
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		&= ~(0x1 << 4);
	// CEN bit at pos 0 > disable while setting registers
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		&= ~(0x1 << 0);
	// TIMx_PSC
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_PSC_OFFSET)) 		= PSC;
	// TIMx_ARR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_ARR_OFFSET)) 		= ARR;
	// Set OCM bits in TIMx_CCMR1 → PWM mode 1 (110)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCMR1_OFFSET))		&= ~(0x7 << 4);
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCMR1_OFFSET))		|= (0x6 << 4);
	// Set OC1PE = 1 in TIMx_CCMR1 (preload enable)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCMR1_OFFSET))		|= (0x1 << 3);
	// Set TIMx_CCR1 (initial duty cycle) D = CCR1 / (ARR+1)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCR1_OFFSET))		= g_CCR;
	// Set CC1E = 1 in TIMx_CCER (enable channel output to pin)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCER_OFFSET))		|= (0x1 << 0);
	// Write UG = 1 in TIMx_EGR (force update — loads PSC/ARR into shadow registers)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_EGR_OFFSET))		|= (0x1 << 0);
	// Set CEN = 1 in TIMx_CR1 (start counter)
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET))		|= (0x1 << 0);
}
uint32_t millis(){
	uint32_t static overflow_count=0;

	if((*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) & (0x1 << 0))){ //Check UIF (bit 0) is set (overflow)
		// Clear UIF — must happen before next wait
		*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) &= ~(0x1 << 0);
		 overflow_count++;
	}
	return overflow_count ; // only ms resolution
}
/*Timer clock after prescaler: 16 MHz / (159+1) = 100,000 Hz
One tick = 1/100,000 = 10 µs
One full CNT cycle (ARR=99): 100 ticks × 10 µs = 1 ms ✓
So overflow_count increments every 1 ms — the unit holds. millis() is still valid.*/

void fade(uint32_t* start){
	uint32_t fade=0;
	while(fade <= 99){ // ARR = 99
		// Set TIMx_CCR1 (initial duty cycle) D = CCR1 / (ARR+1)
		*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCR1_OFFSET))		= fade++;
		//delay
		while( (millis() - *start) < 10 );
		*start +=10;
	}
	while(fade > 0){ // ARR = 99
		// Set TIMx_CCR1 (initial duty cycle) D = CCR1 / (ARR+1)
		*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CCR1_OFFSET))		= --fade;
		//delay
		while( (millis() - *start) < 10 );
		*start +=10;
	}
}
