/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    22-4-2026
 *
 * Description:
 *   This STM32 microcontroller program initializes GPIO and UART
 *   communication, then enters an infinite loop that receives commands
 *   via UART, echoes them back, and parses them for execution. The
 *   program also initializes an LED and provides a command-line
 *   interface over serial communication.
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include 	<stdint.h>
#include 	"stm32f46re.h"
#include 	"led.h"
#include 	"uart.h"
#include 	"parser.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//GPIO Address Space
#define RCC_AHB1ENR_OFFSET 		0x30 // GPIOA bit 0, GPIO B bit 1
//UART Clock Address Space
#define RCC_APB1ENR_OFFSET 		0x40 // USART2 bit 17


//GPIOA Address Space			D2 = PA10
#define	GPIOA_MODER_OFFSET		0x00 // 00 input, 01 GPIO, bit 20-21 for PA10
#define	GPIOA_ODR_OFFSET		0x14 // bit 10 for PA10
#define	GPIOA_AFRL_OFFSET		0x20 // Alternate functions, bit [11:8] for for PA2 // UART = AF7

int main(void)
{
	//Init GPIO
	//Enable clock for GPIOA
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET))	|= 0x1;
	//Enable clock for USART
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|= (0x1 << 17);

	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET))	|= (0x2 << 2*2); //Alternate function
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET))	|= (0x7 << 4*2); //AF 7 for Tx
	// Uart on pin PA3 Rx
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) |= (0x2 << 2*3); //Alternate Function mode (MODER bits [7:6])
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET))  |= (0x7 << 4*3); // AF7 (AFRL bits [15:12])

	// USART2 Config
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_BRR_OFFSET))	|= (0x8B); // Baudrate

	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_CR1_OFFSET))	|= (0x1 << 3); //UART Enable TE - bit 3
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= (0x1 << 2); //UART Enable RE - bit 2
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_CR1_OFFSET))	|= (0x1 << 13); //UART Enable UE - bit 13

	led_init();

	char input[BUFFERSIZE];
    /* Loop forever */
	uart_send_string("Ready for command:\r\n");
	for(;;){
		// Read the entire line
		uart_receive_string(input, BUFFERSIZE);
		// Echo line
		uart_send_string(input);
		uart_send_string("\r\n");
		// Parse command
		parse_command(input);


	}
}







