/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t millis();

int main(void)
{
    //Clock init GPIOA
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) |= 0x1;
	//Clock init timer
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) |= 0x1;

	//Init PA10/D2 as LED output
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET))  |= (0x01 << (2 * 10)); // GPIO mode
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) 	|= (0x1 << 10); // Turn LED on

	// Init timer
			// 	Tim2 Input Clk = 16 MHz (default) --> APB1 prescaler /1, default
			// 	PSC = 15999 --> 16 Mhz / 15999+1 	= 1000 Hz
			//	ARR = 999 	--> 1000 / 999+1 		= 1 Hz
	// TIM2_CR1
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) &= ~(0x1 << 4); // DIR bit at pos 4 > 0 is counting up
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) &= ~(0x1 << 0); // CEN bit at pos 0 > disable while setting registers

	// TIMx_PSC
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_PSC_OFFSET)) = 15999; // PSC = 15999
	// TIMx_ARR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_ARR_OFFSET)) = 999; // DIR bit at pos 4 > 0 is counting up
	// TIMx_SR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) &= ~(0x1); // Bit 0 checks for overflow, clear by software, init to zero
	// TIMx_EGR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_EGR_OFFSET)) |= (0x1 << 0); // Manually create event to update shadow registers
	// Enable TIM2
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) |= (0x1 << 0); // CEN bit at pos 0 > Enable after setting up

	/* Loop forever */
	uint32_t start = millis();
	for(;;){
		// Wait until UIF (bit 0) is set
		while( (millis() - start) < 1000 );
		start +=1000;
		// Toggle LED
		*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) 	^= (0x1 << 10);
	}
}

uint32_t millis(){
	uint32_t static overflow_count=0;

	if((*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) & (0x1 << 0))){ //Check UIF (bit 0) is set (overflow)
		// Clear UIF — must happen before next wait
		*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) &= ~(0x1 << 0);
		 overflow_count++;
	}
	return overflow_count * (*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_ARR_OFFSET))+1) + (*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CNT_OFFSET))) ;
}
