/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    10-5-2026
 *
 * Description:
 *   This STM32F446RE microcontroller program interfaces with a BMP280
 *   temperature/pressure sensor via SPI and displays readings on an
 *   SH1107 OLED display, while also outputting sensor data through
 *   UART for debugging. The program continuously reads sensor data in
 *   a loop, validates the BMP280 connection, and formats the
 *   temperature and pressure measurements for both display and serial
 *   output.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446re.h"
#include "spi.h"
#include "bmp280.h"
#include "uart.h"
#include "sh1107.h"
#include "string.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define NDATA 10

void init_clocks(void);


int main(void)
{
    init_clocks();
    //SPI
    init_gpio();
	init_spi();

	//UART for debugging
	init_uart();

	// DMA init
	uint8_t memory[NDATA];
	init_dma_rx(memory, NDATA);
	init_dma_tx(memory, NDATA);


	//fixed (earlier) reading to test the OLED
	sh1107_init();
	sh1107_clear();
	uint8_t framebuffer[2048];
	memset(framebuffer, 0, 2048);
	sh1107_draw_string(framebuffer, 0, 0, "Temp: 19.35C");
	sh1107_draw_string(framebuffer, 0, 2, "Pres: 1013.72hPa");
	sh1107_send_cmd(0xAE);  // Display OFF
	sh1107_oled_dma_write(framebuffer);
	sh1107_send_cmd(0xAF);  // Display ON

	//Compensation parameter for BMP280
	comp_param_t cp;
	bmp280_ctrl_meas();
	bmp280_comp_params(&cp);
	uart_send_string("Ready for Testing:\r\n");
	/* Loop forever */
	char output_str[50];
	for(;;){
		bmp280_read_burst(0xD0, NDATA, memory);
		uint8_t id = memory[1];
		if (id == 0x58){
		    uart_send_string("BMP280 OK: 0x58\r\n");
		    int32_t T = bmp280_read_temp(&cp);
		    sprintf(output_str, "Temperature: %ld.%02ldC\r\n", T/100, T%100);
		    uart_send_string(output_str);
		    int32_t P = bmp280_read_pressure(&cp);
		    sprintf(output_str, "Pressure: %ld.%02ldhPa\r\n", P/100, P%100);
		    uart_send_string(output_str);
		} else {
		    uart_send_string("BMP280 FAIL\r\n");
		}
		for(volatile int i=0; i < 1000000 ; i++){}; // simple delay
	}
}

void init_clocks(void){
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 	(3u << 0);		// Bit 0 and Bit 1 for GPIOA/GPIOB
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 	(1u << 22);		// Bit 22 for DMA2
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB2ENR_OFFSET))	|= 	(1u << 12);		// Bit 12 for SPI1
}
