/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    31-5-2026
 *
 * Description:
 *   This is an embedded C program for an STM32F446RE microcontroller
 *   that implements a real-time system using FreeRTOS to read sensor
 *   data from an MPU6050 IMU via I2C, log the data, and transmit it
 *   over UART. The system uses multiple tasks, queues, semaphores, and
 *   timers to manage concurrent operations in a structured pipeline
 *   architecture.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "stm32f446re.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "timers.h"

#include "timer.h"
#include "uart.h"
#include "i2c.h"
#include "mpu6050.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define DELAY_VALUE		1000
#define WAKE_UP_DELAY	10000
#define HEARTBEAT_PERIOD	5000
#define SENSOR_PERIOD	1000
#define STR_LEN 		64
#define N_TASKS 		10	//Oversized

QueueHandle_t xQueue1;
QueueHandle_t xQueue2;
QueueHandle_t xQueueUARTRx;
SemaphoreHandle_t xSemaphore;
SemaphoreHandle_t xMutexUart;
TimerHandle_t xTimer;
TimerHandle_t xTimerSensor;
TaskHandle_t xUARTTaskHandle;
TaskHandle_t xUART_RX_TaskHandle;
TaskHandle_t xSensorTaskHandle;
TaskHandle_t xLogTaskHandle;

TaskStatus_t pxTaskStatusArray[N_TASKS];


void vApplicationTickHook(void){}
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){
	uart_send_string("Stack Overflow detected! Task: ");
	uart_send_string(pcTaskName);
	uart_send_string("\r\n");

	taskDISABLE_INTERRUPTS();
	//Spin loop - infinite loop to be caught by debugger
	for(;;);
}
void vApplicationIdleHook(void){}
void vApplicationMallocFailedHook(void){}

void vSensorReadTask(void *pvParameters );
void vLogTask(void *pvParameters );
void vUARTTask(void *pvParameters );
void vUART_Rx_Task(void *pvParameters );

void watchdog( TimerHandle_t xTimer );
void vSensorTimer (TimerHandle_t xTimerSensor );
volatile bool b_timeout = false;


//vSensorReadTask — polls mpu6050_read_data(), posts mpu6050_data_t to xQueue1
//vLogTask — receives from xQueue1, formats, posts string to xQueue2
//vUARTTask — receives from xQueue2, transmits over UART

int main(void)
{
// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)CPACR) |= ((3UL << 10*2) | (3UL << 11*2));
// UART
	uart_gpio_init();
	uart_init();
	xSemaphore = xSemaphoreCreateBinary();
////Timer
//	timer2_init(); -- No longer needed in final part of exercise
//MPU6050
	i2c_init_gpio();
	i2c_init();
	uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
	mpu6050_init(mpu_addr);
	for(volatile int i = 0; i < WAKE_UP_DELAY; i++);

//-- Kernel Object ---
	xQueue1 		= xQueueCreate( 5, sizeof(mpu6050_data_t));  	// mpu6050	--> vSensorReadTask Polls 	--> Q1 	(Acquire)
	xQueue2 		= xQueueCreate( 5, sizeof(char)*STR_LEN);  		// Q1 		--> vLogTask 				--> Q2	(Process)
																// Q2		--> vUARTTask				--> UART (Transmit)
	xQueueUARTRx 	= 	xQueueCreate( 20, sizeof(char));
	xMutexUart 		= 	xSemaphoreCreateMutex();

//--- Tasks	----
	xTaskCreate(vSensorReadTask,				// Task function
				"SensorReadTask",						// Task name
				256,							// Stack Size
				(void*)(uintptr_t)mpu_addr,		// Parameters to function
				1,								// Priority
				&xSensorTaskHandle);			// Handle for task
	xTaskCreate(vLogTask,	"LogTask",	512, NULL, 1,	&xLogTaskHandle);
	xTaskCreate(vUARTTask,	"UARTTask", 256, NULL, 1,	&xUARTTaskHandle);
	xTaskCreate(vUART_Rx_Task,	"UART_Rx_Task", 256, NULL, 1,	&xUART_RX_TaskHandle);

//--- Timer	 ----
	xTimer = xTimerCreate( "Heartbeat Timer",			// name
								HEARTBEAT_PERIOD,		// Period
								pdTRUE,					// Auto-reload or not
								(void *) 0,				// ID
								&watchdog );
	xTimerSensor = xTimerCreate( "Sensor Timer",		// name
								SENSOR_PERIOD,			// Period
								pdTRUE,					// Auto-reload or not
								(void *) 1,				// ID
								&vSensorTimer );
	if(xTimer == NULL || xTimerSensor == NULL){
			uart_send_string("Failed to start timers!\r\n");
	}
	xTimerStart(xTimer, 0);
	xTimerStart(xTimerSensor, 0);
//-- Scheduler	---
	uart_send_string("Ready to schedule:\r\n");
	vTaskStartScheduler();
    /* Loop forever */

	for(;;);
}

void vSensorReadTask(void *pvParameters){
	uint8_t dev_addr = (uint8_t)(uintptr_t)pvParameters;
	mpu6050_data_t data;
	for(;;){
		if(ulTaskNotifyTake(pdTRUE,10)){
//			xSemaphoreTake(xSemaphore, portMAX_DELAY);  // Replaces software-based vTaskDelay(pdMS_TO_TICKS(DELAY_VALUE));
			mpu6050_read_data(dev_addr, &data);
			if(data.accel_x == 0 && data.accel_y == 0 && data.accel_z == 0){
				// likely wrong read
			}else{
				b_timeout = false;
				xQueueSend( xQueue1, 	(void *) &data, 0);
			}
		}
	}
}
void vLogTask(void *pvParameters){
	mpu6050_data_t sensor_read;
	char output_str[STR_LEN];
	for(;;){
		if(xQueueReceive(	xQueue1, 	(void *) &sensor_read, portMAX_DELAY) == pdTRUE){
			snprintf(output_str, sizeof(output_str),
							"%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\r\n",
							(float)sensor_read.accel_x/16384,	(float)sensor_read.accel_y/16384,	(float)sensor_read.accel_z/16384, 		//2^15 / 2g (sensitivity)
							(float)sensor_read.gyro_x/131,		(float)sensor_read.gyro_y/131,		(float)sensor_read.gyro_z/131			//2^15 / 250g (sensitivity)
							);
			xQueueSend( xQueue2, 	(void *) output_str, 0);
		}
	}
}
void vUARTTask(void *pvParameters){
	char output_str[STR_LEN];
	for(;;){
		if(ulTaskNotifyTake( pdTRUE,0)){
			xSemaphoreTake(xMutexUart, portMAX_DELAY);
			uart_send_string("ERROR: No heartbeat from sensor!\r\n");
			xSemaphoreGive(xMutexUart);
		}
		if(xQueueReceive(	xQueue2, 	(void *) &output_str, 100) == pdTRUE){
			xSemaphoreTake(xMutexUart, portMAX_DELAY);
			uart_send_string(output_str);
			xSemaphoreGive(xMutexUart);
		}
	}
}

void vUART_Rx_Task(void *pvParameters ){
	char item;
	char command[20];
	uint8_t index = 0;
	uint32_t period = 0;
	for(;;){
		if(xQueueReceive(	xQueueUARTRx, 	(void *) &item, 100) == pdTRUE){
			if(item == '\r'){
				// command finished
				command[index]='\0';
				xSemaphoreTake(xMutexUart, portMAX_DELAY);
				uart_send_string(command);
				uart_send_string("\r\n");
				xSemaphoreGive(xMutexUart);
				if(strcmp(strtok(command, " "), "log") == 0){
					period = atoi(strtok(NULL, " "));
					if(period < 100){
						period = 100; // lower bound, to protect on false inputs
					}
					// change period in timer
					xTimerChangePeriod(xTimerSensor, pdMS_TO_TICKS(period), 0);

				}else if (strcmp(command, "hwm")==0){
					UBaseType_t uxCount = uxTaskGetNumberOfTasks();
					uxTaskGetSystemState(pxTaskStatusArray, uxCount, NULL);
					char hwm_str[STR_LEN];
					xSemaphoreTake(xMutexUart, portMAX_DELAY);
					for(uint8_t task_i=0; task_i < uxCount; task_i++){

						uart_send_string("Task: ");
						uart_send_string(pxTaskStatusArray[task_i].pcTaskName);
						uart_send_string(" - HWM Value: ");
						snprintf(hwm_str, sizeof(hwm_str), "%lu\r\n", pxTaskStatusArray[task_i].usStackHighWaterMark);
						uart_send_string(hwm_str);
					}
					xSemaphoreGive(xMutexUart);
				}else if (strcmp(command, "mem")==0){
					char heap_str[STR_LEN];
					xSemaphoreTake(xMutexUart, portMAX_DELAY);
					snprintf(heap_str, sizeof(heap_str), "Current free Heap available: %u\r\n", xPortGetFreeHeapSize());
					uart_send_string(heap_str);
					snprintf(heap_str, sizeof(heap_str), "Minimal free Heap Ever available: %u\r\n", xPortGetMinimumEverFreeHeapSize());
					uart_send_string(heap_str);
					xSemaphoreGive(xMutexUart);
				}
				//	reset for next command
				index = 0;
			}else
			{
				command[index] = item;
				index++;
				index = index % 20; // protect against overflow
			}
		}
	}
}

void watchdog( TimerHandle_t xTimer ){
	if(b_timeout){
		xTaskNotifyGive(xUARTTaskHandle);			//notify vUARTTask
	}else{
		b_timeout = true; 		//reset -- sensor should set before next timer-callback
	}
}

void vSensorTimer (TimerHandle_t xTimerSensor ){
	xTaskNotifyGive(xSensorTaskHandle);
}
