/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MAX_LENGTH 64

void TIM2_IRQHandler(void);
void EXTI15_10_IRQHandler(void);
void USART2_init(void);
void USART2_IRQHandler(void);
void uart_send_char(uint8_t c);
void uart_send_string(const char* str);
uint32_t millis();

volatile uint32_t static overflow_count=0;


//variables for string handling
char buffer[MAX_LENGTH];
volatile uint8_t head = 0;
volatile uint8_t tail = 0;

int main(void)
{
	//Clock init GPIOA/GPIOB
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 0x3; //11 for GPIOA and B
	//Clock init timer
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) 	|= 0x1;
	//Clock init SYSCNFG
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)) 	|= (0x1 << 14); //bit 14 for SYSCFG

	//Init PA10/D2 as LED output
	// Clear both bits for PA10 first, then set the desired mode
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	&= ~(0x3 << (2 * 10));  // clear
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	|=  (0x01 << (2 * 10));  // set, GPIO Mode
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) 	|= (0x1 << 10); // Turn LED on

	//Init PB10/D6 as Button input
	*((volatile uint32_t *)(GPIOB_BASE_ADDR + GPIOB_MODER_OFFSET)) 	&= ~(0x3 << (2 * 10));  // clear, set 00 as input mode

	// Init timer
			// 	Tim2 Input Clk = 16 MHz (default) --> APB1 prescaler /1, default
			// 	PSC = 15999 --> 16 Mhz / 15999+1 	= 1000 Hz
			//	ARR = 499 	--> 1000 / 499+1 		= 2 Hz
	// TIM2_CR1
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		&= ~(0x1 << 4); // DIR bit at pos 4 > 0 is counting up
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		&= ~(0x1 << 0); // CEN bit at pos 0 > disable while setting registers
	// TIMx_PSC
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_PSC_OFFSET)) 		= 15999; // PSC = 15999
	// TIMx_ARR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_ARR_OFFSET)) 		= 499; // DIR bit at pos 4 > 0 is counting up
	// TIMx_DIER
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_DIER_OFFSET)) 		|= (0x1 << 0); // Enable Interrupt mode
	// TIMx_EGR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_EGR_OFFSET)) 		|= (0x1 << 0); // Manually create event to update shadow registers
	// TIMx_SR
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) 		&= ~(0x1); // Bit 0 checks for overflow, clear by software, init to zero
	// Enable TIM2
	*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CR1_OFFSET)) 		|= (0x1 << 0); // CEN bit at pos 0 > Enable after setting up

	//Configure NVIC
	*((volatile uint32_t*)(NVIC_BASE_ADDR + NVIC_ISER0_OFFSET))		|= (0x1 << TIM2_POS); //NVIC_EnableIRQ(TIM2_IRQn);
	*((volatile uint32_t*)(NVIC_BASE_ADDR + NVIC_ISER1_OFFSET))		|= (0x1 << EXTI15_10_POS);

	//Configure SYSCFG for EXTI-interrupt
	*((volatile uint32_t*)(SYSCFG_BASE_ADDR + SYSCFG_EXTICR3_OFFSET))	|= (0x0001 << 8); //bit 10 for PB10

	//Configure EXTI for button-interrupt
	*((volatile uint32_t*)(EXTI_BASE_ADDR + EXTI_IMR_OFFSET))		|= (0x1 << 10); //bit 10 for PB10
	*((volatile uint32_t*)(EXTI_BASE_ADDR + EXTI_RTSR_OFFSET))		|= (0x1 << 10); //bit 10 for PB10

	USART2_init();


    /* Loop forever */
	char str[MAX_LENGTH];
	uint8_t index = 0;
	for(;;){
	    if(head != tail)
	    {
	        if (buffer[tail] == '\r' || buffer[tail] == '\n')
	        {
	            if (index > 0)
	            {
	                str[index++] = '\r';
	                str[index++] = '\n';
	                str[index]   = '\0';
	                uart_send_string(str);
	                index = 0;
	            }
	            tail = (tail + 1) % MAX_LENGTH;
	        }
	        else
	        {
	            if (index < MAX_LENGTH - 3)
	            {
	                str[index++] = buffer[tail];
	            }
	            tail = (tail + 1) % MAX_LENGTH;
	        }
	    }
	}
}

void USART2_init(void){
	// 	Enable Clock, APB1ENR bit 17
	*((volatile uint32_t*)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) 	|= 	(0x1 << 17);
	// 	Enable Alternate function on GPIOA bit2/3 (AF7)
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	&= 	~(0x3 << 2*2);
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	&= 	~(0x3 << 2*3);
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	|= 	(0x2 << 2*2);
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) 	|= 	(0x2 << 2*3);
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET)) 	|= 	(0x7 << 4*2);
	*((volatile uint32_t*)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET)) 	|= 	(0x7 << 4*3);
	// 	Set Baudrate
	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_BRR_OFFSET)) 	= 	0x8B; // BR 115200
	// 	Enable TE
	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= 	(0x1 << 3);
	// 	Enable RE
	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= 	(0x1 << 2);
	//	Enable Interrupt RXNEIE
	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= 	(0x1 << 5);
	// 	Enable NVIC
	*((volatile uint32_t*)(NVIC_BASE_ADDR + NVIC_ISER1_OFFSET))		|= (0x1 << USART2_POS);
	// 	Enable USART
	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= 	(0x1 << 13);
}
void USART2_IRQHandler(void){
	if( *((volatile uint32_t*)(USART2_BASE_ADDR + USART_SR_OFFSET)) & (0x1 << 5) ){ // Check if interrupt fired because data has been received
		buffer[head]= *((volatile uint32_t *)(USART2_BASE_ADDR + USART_DR_OFFSET));
		head = (head + 1) % MAX_LENGTH; // reset circular buffer to beginning

		// Interrupt cleared automatically by hardware after reading clear after reading
	} // refactored to circular buffer
}

void uart_send_char(uint8_t c){
	while(!(*((volatile uint32_t *)(USART2_BASE_ADDR + USART_SR_OFFSET)) & (0x1 << 7))){}; // Wait until TXE is 1 (Tx data register empty)
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_DR_OFFSET)) = c;
}
void uart_send_string(const char* str){
	while((*str)!='\0'){
		uart_send_char(*str);
		str++;
	}
}

void TIM2_IRQHandler(void){
	if( (*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) & (0x1 << 0)) ){
		// Toggle LED
		*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) 	^= (0x1 << 10);
		overflow_count++;
		//Clear overflow bit
		*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_SR_OFFSET)) &= ~(0x1);
	}
}
void EXTI15_10_IRQHandler(void){
	static uint32_t last_press = 0;
	uint32_t now = millis();
	if (now - last_press > 500) {
		last_press = now;
		if( (*((volatile uint32_t*)(EXTI_BASE_ADDR + EXTI_PR_OFFSET)) & (0x1 << 10)) ){
			// Clear LED
			*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) 	&= ~(0x1 << 10);
			// Toggle Timer Interrupt --> LED will stop blinked / Start blinking
			*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_DIER_OFFSET)) ^= (0x1 << 0);
		}
	}
	//Clear bit by writing 1 to it
	*((volatile uint32_t*)(EXTI_BASE_ADDR + EXTI_PR_OFFSET)) |= (0x1 << 10);
}
uint32_t millis(){
	return overflow_count * (*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_ARR_OFFSET))+1) + (*((volatile uint32_t*)(TIM2_BASE_ADDR + TIMx_CNT_OFFSET))) ;
}

