/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    12-4-2026
 *
 * Description:
 *   This STM32 microcontroller program controls an LED connected to
 *   pin PA5 that turns on when a push button connected to pin PC13 is
 *   pressed, using direct register manipulation to configure GPIO
 *   ports and read/write pin states. The program runs in an infinite
 *   loop, keeping the LED off by default and illuminating it only
 *   while the button is actively pressed.
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 		0x40023800
#define RCC_AHB1ENR_OFFSET 	0x30

#define GPIOA_BASE_ADDR		0x40020000
#define	GPIOA_MODER_OFFSET	0x00	// gpio 01
#define	GPIOA_ODR_OFFSET	0x14

#define GPIOC_BASE_ADDR		0x40020800
#define	GPIOC_MODER_OFFSET	0x00 // input 00
#define	GPIOC_IDR_OFFSET	0x10


int main(void)
{
	//Enable RCC CLock on AHB1 (GPIOA)
	*((volatile uint32_t *) (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) |= (1 << 0);//GPIOA is at bit 0

	//Enable RCC CLock on AHB1 (GPIOA)
	*((volatile uint32_t *) (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) |= (1 << 2);//GPIOC is at bit 2

	//Set PA5 (LED Pin) to GPIO Mode
	*((volatile uint32_t *) (GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) |= (1 << 10); //MODER5 (b10-11) = 0b01

	//Set PC13 (BTN) to INPUT mode
	*((volatile uint32_t *) (GPIOC_BASE_ADDR + GPIOC_MODER_OFFSET)) |= (00 << 26); //MODER13 (b26-27) = 0b00


    /* Loop forever */
	for(;;)
	{
		//Pull PA5 Pin LOW
		*((volatile uint32_t *) (GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) &= ~(1 << 5);
		//Read PSH button Value
		volatile int pushed = (*((volatile uint32_t *) (GPIOC_BASE_ADDR + GPIOC_IDR_OFFSET)) >> 13) & 1;
		while(!pushed)
		{
			//Pull PA5 Pin HIGH
			*((volatile uint32_t *) (GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) |= (1 << 5);

			pushed = (*((volatile uint32_t *) (GPIOC_BASE_ADDR + GPIOC_IDR_OFFSET)) >> 13) & 1;
		}
	}
}
