# meta-avindeli/conf/machine/raspberrypi4-64-avindeli.conf
require conf/machine/raspberrypi4-64.conf

ENABLE_UART = "1"
RPI_EXTRA_CONFIG = "dtoverlay=mydev"
RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/mydev.dtbo"