/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    17-5-2026
 *
 * Description:
 *   This STM32F446RE embedded application initializes SPI, UART, and
 *   GPIO peripherals along with the necessary RCC clocks, then
 *   repeatedly polls a BMP280 pressure/temperature sensor via SPI and
 *   reports its WHO_AM_I register result over UART for debugging
 *   purposes.
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"
#include "spi.h"
#include "bmp280.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_clocks(void);


int main(void)
{
    init_clocks();
    //SPI
    init_gpio();
	init_spi();
	//UART for debugging
	init_uart();
	/* Loop forever */
	uart_send_string("Ready for Testing:\r\n");
	for(;;){
		uint8_t id = bmp280_read_who_am_i();
		if (id == 0x58){
		    uart_send_string("BMP280 OK: 0x58\r\n");
		} else {
		    uart_send_string("BMP280 FAIL\r\n");
		}
		for(int i=0; i < 1000000 ; i++){}; // simple delay
	}
}

void init_clocks(void){
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 	(3u << 0);		// Bit 0 and Bit 1 for GPIOA/GPIOB
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB2ENR_OFFSET))	|= 	(1u << 12);		// Bit 12 for SPI1
}

