/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    30-4-2026
 *
 * Description:
 *   This is an STM32F446RE microcontroller program that implements a
 *   command-line interface over UART, receiving text commands from a
 *   user, echoing them back, and parsing them to control various
 *   peripherals including PWM output, LED blinking, and timers. The
 *   program runs in an infinite loop waiting for user input after
 *   initializing the system clocks and peripheral modules.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"
#include "parser.h"
#include "uart.h"
#include "timer.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_clocks(void);

int main(void)
{
	init_clocks();
	init_gpio_pa0_pwm();
	init_blink();
	init_uart();

	char input[BUFFERSIZE];
	/* Loop forever */
	uart_send_string("Ready for command:\r\n");
	for(;;){
		// Read the entire line
		if(uart_receive_string(input, BUFFERSIZE)){
			// Echo line
			uart_send_string(input);
			uart_send_string("\r\n");
			// Parse command
			parse_command(input);
		}
	}
}

void init_clocks(void){
	//Clock init GPIOA/GPIO
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 0x1; //01 for GPIOA
	//Clock init timer
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) 	|= 0x1;
}


