/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    22-5-2026
 *
 * Description:
 *   This STM32F446RE bare-metal firmware initializes I2C, UART, and
 *   GPIO clocks, then repeatedly polls a BMP280 pressure sensor over
 *   I2C and reports whether the device ID reads the expected value
 *   (0x58) via UART. It also includes an `i2c_scan` utility function
 *   that probes all standard I2C addresses and prints any responding
 *   devices over UART.
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"
#include "i2c.h"
#include "bmp280.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_clocks(void);

int main(void)
{
    init_clocks();
    init_i2c_gpio();
    i2c_init();
    init_uart();

    uart_send_string("Ready for Testing:\r\n");
    for(;;){
        uint8_t id = bmp280_i2c_read_who_am_i();
        if (id == 0x58){
            uart_send_string("BMP280 OK: 0x58\r\n");
        } else {
            uart_send_string("BMP280 FAIL\r\n");
        }
        for(volatile int i=0; i < 1000000 ; i++){};
    }
}
void init_clocks(void){
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 	(3u << 0);		//  Bit 0,1 for GPIOA/B
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|=  (1u << 17);		//Enable clock for USART
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|= 	(1u << 21);		// Bit 21 for I2C1
}
void i2c_scan(void){
    for(uint8_t addr = 0x08; addr < 0x78; addr++){
        // Generate START
        I2C1_CR1 |= I2C_CR1_START;
        while(!(I2C1_SR1 & I2C_SR1_SB));

        // Send address
        I2C1_DR = (addr << 1 | 0);

        // Wait for ADDR (ACK) or AF (NACK)
        while(!(I2C1_SR1 & (I2C_SR1_ADDR | I2C_SR1_AF)));

        if(I2C1_SR1 & I2C_SR1_ADDR){
            // ACK — device found, clear ADDR
            (void)I2C1_SR1;
            (void)I2C1_SR2;
            uart_send_string("Device found at: 0x");
            uart_send_char("0123456789ABCDEF"[addr >> 4]);
            uart_send_char("0123456789ABCDEF"[addr & 0x0F]);
            uart_send_string("\r\n");
        } else {
            // NACK — clear AF
            I2C1_SR1 &= ~I2C_SR1_AF;
        }
        // Generate STOP
        I2C1_CR1 |= I2C_CR1_STOP;
        for(volatile int i = 0; i < 10000; i++);
    }
    uart_send_string("Scan complete.\r\n");
}
