/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//GPIO Clock Address Space
#define RCC_BASE_ADDR			0x40023800
//GPIO Address Space
#define RCC_AHB1ENR_OFFSET 		0x30 // GPIOA bit 0, GPIO B bit 1
//UART Clock Address Space
#define RCC_APB1ENR_OFFSET 		0x40 // USART2 bit 17


//USART2 Address Space
#define USART2_BASE_ADDR		0x40004400
#define USART_SR_OFFSET			0x00 // 8bit for data transfer
#define USART_DR_OFFSET			0x04 // 8bit for data transfer
#define	USART_BRR_OFFSET		0x08 // Baudrate --> 0x8B for desired BR [15:4]_Mantissa - [3:0] Fraction
#define USART_CR1_OFFSET		0x0C // Control register - bit15 Over8 / bit 12 wordlength M / bit 3 TE
#define USART_CR2_OFFSET		0x10 // Control register - bit15 Over8 / bit 12 wordlength M / bit 3 TE
#define USART_CR3_OFFSET		0x14 // Control register - bit15 Over8 / bit 12 wordlength M / bit 3 TE

//GPIOA Address Space			D2 = PA10
#define GPIOA_BASE_ADDR			0x40020000
#define	GPIOA_MODER_OFFSET		0x00 // 00 input, 01 GPIO, bit 20-21 for PA10
#define	GPIOA_ODR_OFFSET		0x14 // bit 10 for PA10
#define	GPIOA_AFRL_OFFSET		0x20 // Alternate functions, bit [11:8] for for PA2 // UART = AF7

void uart_send_char(uint8_t c);
void uart_send_string(char* str);

int main(void)
{
	//Init GPIO
	//Enable clock for GPIOA
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET))	|= 0x1;
	//Enable clock for USART
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|= (0x1 << 17);
	//Init LED on pin PA10
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET))	|= (0x1 << 2*10);
	//Init UART on pin PA2
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET))	|= (0x2 << 2*2); //Alternate function
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_AFRL_OFFSET))	|= (0x7 << 4*2); //AF 7 for Tx


	// USART2 Config
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_BRR_OFFSET))	|= (0x8B); // Baudrate

	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_CR1_OFFSET))	|= (0x1 << 3); //Uart Enable TE - bit 3
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_CR1_OFFSET))	|= (0x1 << 13); //Uart Enable UE - bit 13


    /* Loop forever */
	for(;;){
		uart_send_char('A');
		uart_send_string(" Hello World!\r\n");
		for(volatile int count = 0; count < 1000000; count++); // mimic delay
	}
}


void uart_send_char(uint8_t c){
	while(!(*((volatile uint32_t *)(USART2_BASE_ADDR + USART_SR_OFFSET)) & (0x1 << 7))){}; // Wait until TXE is 1 (Tx data register empty)
	*((volatile uint32_t *)(USART2_BASE_ADDR + USART_DR_OFFSET)) = c;

	return;
}

void uart_send_string(char* str){
	while((*str)!='\0'){
		uart_send_char(*str);
		str++;
	}
}




