/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "FreeRTOS.h"
#include "stm32f446re.h"
#include "task.h"
#include "queue.h"
#include "uart.h"
#include "i2c.h"
#include "mpu6050.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define DELAY_VALUE		1000
#define WAKE_UP_DELAY	10000
#define STR_LEN 		64


void vApplicationTickHook(void){}
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){}
void vApplicationIdleHook(void){}
void vApplicationMallocFailedHook(void){}

void vSensorReadTask(void *pvParameters );
void vLogTask(void *pvParameters );
void vUARTTask(void *pvParameters );

QueueHandle_t xQueue1;
QueueHandle_t xQueue2;
//
//ISR / UART terminal — retired
//vSensorReadTask — polls mpu6050_read_data(), posts mpu6050_data_t to xQueue1
//vLogTask — receives from xQueue1, formats, posts string to xQueue2
//vUARTTask — receives from xQueue2, transmits over UART

int main(void)
{
	// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)CPACR) |= ((3UL << 10*2) | (3UL << 11*2));
	uart_gpio_init();
	uart_init();

	//I2C
	i2c_init_gpio();
	i2c_init();
	uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
	mpu6050_init(mpu_addr);
	for(volatile int i = 0; i < WAKE_UP_DELAY; i++);

	xQueue1 = xQueueCreate( 5, sizeof(mpu6050_data_t));  	// mpu6050	--> vSensorReadTask Polls 	--> Q1 	(Acquire)
	xQueue2 = xQueueCreate( 5, sizeof(char)*STR_LEN);  		// Q1 		--> vLogTask 				--> Q2	(Process)
															// Q2		--> vUARTTask				--> UART (Transmit)
	xTaskCreate(vSensorReadTask,				// Task function
				"Acquire",				// Task name
				512,		// Stack Size
				(void*)(uintptr_t)mpu_addr,		// Parameters to function
				1,								// Priority
				NULL);							// Handle for task
	xTaskCreate(vLogTask,
				"Process",
				512,
				NULL,
				1,
				NULL);
	xTaskCreate(vUARTTask,
				"Transmit",
				512,
				NULL,
				1,
				NULL);
	uart_send_string("Ready to schedule:\r\n");
	vTaskStartScheduler();
		// Timing to be set-up in a later week
    /* Loop forever */

	for(;;);
}

void vSensorReadTask(void *pvParameters){
	uint8_t dev_addr = (uint8_t)(uintptr_t)pvParameters;
	mpu6050_data_t data;
//	char hwm_str[32];
	for(;;){
		mpu6050_read_data(dev_addr, &data);
		xQueueSend( xQueue1, 	(void *) &data, 0);
//		UBaseType_t uxHighWaterMark = uxTaskGetStackHighWaterMark(NULL);
//		snprintf(hwm_str, sizeof(hwm_str), "SensorRead HWM: %lu\r\n", (uint32_t)uxHighWaterMark);
//		uart_send_string(hwm_str);
		vTaskDelay(pdMS_TO_TICKS(DELAY_VALUE));
	}
}
void vLogTask(void *pvParameters){
	mpu6050_data_t sensor_read;
	char output_str[STR_LEN];
//	char hwm_str[32];
	for(;;){
		if(xQueueReceive(	xQueue1, 	(void *) &sensor_read, portMAX_DELAY) == pdTRUE){
			snprintf(output_str, sizeof(output_str),
							"%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\r\n",
							(float)sensor_read.accel_x/16384,	(float)sensor_read.accel_y/16384,	(float)sensor_read.accel_z/16384, 		//2^15 / 2g (sensitivity)
							(float)sensor_read.gyro_x/131,		(float)sensor_read.gyro_y/131,		(float)sensor_read.gyro_z/131			//2^15 / 250g (sensitivity)
							);
			xQueueSend( xQueue2, 	(void *) output_str, 0);
//			UBaseType_t uxHighWaterMark = uxTaskGetStackHighWaterMark(NULL);
//			snprintf(hwm_str, sizeof(hwm_str), "LogTask HWM: %lu\r\n", (uint32_t)uxHighWaterMark);
//			uart_send_string(hwm_str);
		}
	}
}
void vUARTTask(void *pvParameters){
//	char hwm_str[32];
	char output_str[STR_LEN];
	for(;;){

		if(xQueueReceive(	xQueue2, 	(void *) &output_str, portMAX_DELAY) == pdTRUE){
			uart_send_string(output_str);
//			UBaseType_t uxHighWaterMark = uxTaskGetStackHighWaterMark(NULL);
//			snprintf(hwm_str, sizeof(hwm_str), "UARTTask HWM: %lu\r\n", (uint32_t)uxHighWaterMark);
//			uart_send_string(hwm_str);
		}
	}
}


//void vStartupTask(void *pvParameters){
//    // enable RXNEIE here
//	//	Enable Interrupt RXNEIE
//	*((volatile uint32_t*)(USART2_BASE_ADDR + USART_CR1_OFFSET)) 	|= 	(0x1 << 5);
//    vTaskDelete(NULL);  // delete itself when done
//}
