/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"
#include "timer.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

struct state{
	uint8_t output;
	uint32_t time;
	uint8_t next_state[4];
};
typedef const struct state state_t;

#define goN		0
#define waitN	1
#define	goE		2
#define	waitE	3

state_t FSM[4]={
	{0x21, 5000, {goN, waitN, goN, waitN}},
	{0x11, 1000, {goE, goE, goE, goE}},
	{0x0C, 5000, {goE, goE, waitE, waitE}},
	{0x0A, 1000, {goN, goN, goN, goN}}
};
// Bit position in output byte → GPIO pin number
const uint8_t pin_map[6] = {
    13,  	// bit 0 = East Red
    2,   	// bit 1 = East Yellow
    3,    	// bit 2 = East Green
	8,   	// bit 3 = North Red
	6,  	// bit 4 = North Yellow
	5   	// bit 5 = North Green
};
const uint8_t button_map[2] = {
    10,   	// bit 1 of input = PB10 --> North(/top) sensor
	9,   	// bit 0 of input = PB9 --> East(/bottom) sensor
};

uint8_t current_state;
uint8_t input;


void init_clocks(void);
void init_leds();
void set_outputs(uint8_t output);
uint8_t read_inputs(void);


int main(void)
{
	//Init clocks()
	init_clocks();
	//Init timer
	init_timer();
	//Init LEDs
	init_leds();
	//Init Pushbuttons
	init_button_PB(9);
	init_button_PB(10);
	/* Loop forever */

	current_state = goN;
	for(;;){
		set_outputs(FSM[current_state].output);
		while(overflow_count < FSM[current_state].time);
		overflow_count = 0;
		input = read_inputs();
		current_state = FSM[current_state].next_state[input];
	}
}

void init_clocks(void){
	//Clock init GPIOA/GPIO
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 0x6; //110 for GPIOB + GPIOC
	//Clock init timer
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)) 	|= 0x1;
}
void init_leds(){
	for (uint8_t i = 0; i < 6; i++) {
		init_gpio_PCX(pin_map[i]);
	}
}
void set_outputs(uint8_t output) {
    for (uint8_t i = 0; i < 6; i++) {
        if (output & (1 << i)) {
            *((volatile uint32_t *)(GPIOC_BASE_ADDR + GPIOC_ODR_OFFSET)) |=  (1 << pin_map[i]);
        } else {
            *((volatile uint32_t *)(GPIOC_BASE_ADDR + GPIOC_ODR_OFFSET)) &= ~(1 << pin_map[i]);
        }
    }
}
uint8_t read_inputs(void) {
    uint32_t idr = *((volatile uint32_t *)(GPIOB_BASE_ADDR + GPIOB_IDR_OFFSET));
    uint8_t result = 0;
    for (uint8_t i = 0; i < 2; i++) {
        if (idr & (1 << button_map[i])) {
            result |= (1 << i);
        }
    }
    return result;  // 0b00, 0b01, 0b10, 0b11
}


