/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    6-6-2026
 *
 * Description:
 *   This file initializes an STM32F446RE microcontroller with multiple
 *   peripherals (UART, I2C, SPI, timers) and sensor drivers (MPU6050,
 *   BMP280), then creates and starts an FreeRTOS kernel with four
 *   concurrent tasks for sensor reading, command parsing, and data
 *   logging. The program uses queues, mutexes, and timers to
 *   coordinate inter-task communication and periodic sensor sampling.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f446re.h"
#include "rtos/kernel_objects.h"
#include "app/watchdog.h"

#include "drivers/timer.h"
#include "drivers/uart.h"
#include "drivers/i2c.h"
#include "drivers/spi.h"
#include "drivers/mpu6050/mpu6050.h"
#include "drivers/bmp280/bmp280.h"

#include "tasks/task_cmd.h"
#include "tasks/task_i2c.h"
#include "tasks/task_log.h"
#include "tasks/task_spi.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define WAKE_UP_DELAY		10000

int main(void)
{
// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)CPACR) |= ((3UL << 10*2) | (3UL << 11*2));
// UART
	uart_gpio_init();
	uart_init();
////Timer
	timer2_init(); // starts of disabled
//MPU6050
	i2c_init_gpio();
	i2c_init();
	uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
	mpu6050_init(mpu_addr);
//BMP280
	spi_gpio_init();
	bmp280_spi_gpio_init();
	spi_init();
	bmp280_spi_init();
// Settling delay
	for(volatile int i = 0; i < WAKE_UP_DELAY; i++);

//-- Kernel Object ---
	xQueue_mpu6050 		= xQueueCreate( 5, sizeof(mpu6050_data_t));
	xQueue_bmp280 		= xQueueCreate( 5, sizeof(int32_t));
	xQueueUARTRx 		= xQueueCreate( 20, sizeof(char));
	xMutexUart 			= xSemaphoreCreateMutex();

//--- Tasks	----
	xTaskCreate(vSPITask,				// Task function
				"SPI - BMP280 Task",				// Task name
				128,							// Stack Size
				NULL,		// Parameters to function
				1,								// Priority
				&xSPITaskHandle);			// Handle for task
	xTaskCreate(vI2CTask,	"I2C - MPU6050 Task",	128, (void*)(uintptr_t)mpu_addr, 1,	&xI2CTaskHandle);
	xTaskCreate(vCmdTask,	"Command Parser Task", 256, NULL, 1,	&xCmdTaskHandle);
	xTaskCreate(vLogTask,	"CSV + UART Task", 512, NULL, 1,	&xLogTaskHandle);

//--- Timer	 ----
	xTimerBMP280 = xTimerCreate( "BMP280 Timer",		// Name
								BMP280_PERIOD,			// Period
								pdTRUE,					// Auto-reload or not
								(void *) 1,				// ID
								&vBMP280Timer );
	xTimerHeartBeat = xTimerCreate( "Watchdog Timer",	// Name
								HEARTBEAT_PERIOD,		// Period
								pdTRUE,					// Auto-reload or not
								(void *) 1,				// ID
								&vHeartBeatTimer );
	if(xTimerBMP280 == NULL || xTimerHeartBeat == NULL ){
			uart_send_string("Failed to create timers!\r\n");
	}
//-- Scheduler	---
	uart_send_string("Ready to schedule:\r\n");
	vTaskStartScheduler();
    /* Loop forever */

	for(;;);
}


