/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f446re.h"
#include "i2c.h"
#include "spi.h"
#include "bmp280.h"
#include "mpu6050.h"
#include "uart.h"
#include "systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define NDATA 			10
#define WAKE_UP_DELAY	10000

int main(void)
{
	// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)CPACR) |= ((3UL << 10*2) | (3UL << 11*2));
	//Timer
	systick_init();
    //UART
	uart_gpio_init();
	uart_init();
	//SPI
	spi_gpio_init();
	bmp280_spi_gpio_init();
	spi_init();
	bmp280_spi_init();
	//I2C
	i2c_init_gpio();
	i2c_init();
    uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
    mpu6050_init(mpu_addr);
    for(volatile int i = 0; i < WAKE_UP_DELAY; i++);
    uart_send_string("Ready for Testing:\r\n");
    char input_str[50];
    char output_str[256];
    mpu6050_data_t sensor_read;
    int32_t temperature;
    int32_t pressure;
    bool log_active = true;
    for(;;){
    	uint32_t start = systick_get_ms();
		uint32_t current = start;
		if(uart_receive_string(input_str, 50)){
			if(!strcmp(input_str, "log on")){
				log_active = true;
				uart_send_string("Start logging:\r\n");
			}
			else if(!strcmp(input_str, "log off")){
				log_active = false;
				uart_send_string("Stop logging:\r\n");
			}else{
				uart_send_string("Invalid command:\r\n");
			}
		}
		if(log_active){
		bmp280_spi_read_temp(&temperature);
		bmp280_spi_read_pressure(&pressure);
		mpu6050_read_data(mpu_addr, &sensor_read);
		snprintf(output_str, sizeof(output_str),
				"%lu,%ld.%02ld,%ld.%02ld,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\r\n",
				current, temperature/100, temperature%100, pressure/100, pressure%100,
				(float)sensor_read.accel_x/16384,	(float)sensor_read.accel_y/16384,	(float)sensor_read.accel_z/16384, 		//2^15 / 2g (sensitivity)
				(float)sensor_read.gyro_x/131,		(float)sensor_read.gyro_y/131,		(float)sensor_read.gyro_z/131			//2^15 / 250g (sensitivity)
				);
		uart_send_string(output_str);
		}
		while(current - start < 1000) current = systick_get_ms(); // simple delay
	}
}


