/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    12-4-2026
 *
 * Description:
 *   This STM32 microcontroller program configures GPIO pins to control
 *   an LED that blinks when switch 1 (PA8) is pressed and stops
 *   blinking when switch 2 (PB10) is pressed. The program uses direct
 *   register manipulation to initialize the GPIO peripherals and
 *   implements a simple delay-based blinking pattern on LED pin PA10.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR_BASE_ADDR	0x40023800
#define RCC_AHB1ENR_OFFSET 		0x30 // GPIOA bit 0, GPIO B, bit 1

#define GPIOA_BASE_ADDR			0x40020000
#define	GPIOA_MODER_OFFSET		0x00 // 00 input, 01 GPIO
#define	GPIOA_IDR_OFFSET		0x10
#define	GPIOA_ODR_OFFSET		0x14

#define GPIOB_BASE_ADDR			0x40020400
#define	GPIOB_MODER_OFFSET		0x00 // 00 input, 01 GPIO
#define	GPIOB_IDR_OFFSET		0x10
#define	GPIOB_ODR_OFFSET		0x14 // unused

int main(void)
{
	//Init
	//Enable clock for GPIOA and GPIOB
	*((volatile uint32_t *)(RCC_AHB1ENR_BASE_ADDR + RCC_AHB1ENR_OFFSET)) |= 0x3;

	// SW1/PA8 - Set input-mode
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) |= (0x00 << 2*8);
	// SW2/PB10 - Set input-mode
	*((volatile uint32_t *)(GPIOB_BASE_ADDR + GPIOB_MODER_OFFSET)) |= (0x00 << 2*10);
	// LED pin - PA10 - set output-mode
	*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)) |= (0x01 << 2*10);

    /* Loop forever */
	for(;;)
	{
		volatile int sw1_pushed = (*((volatile uint32_t *)(GPIOA_BASE_ADDR+GPIOA_IDR_OFFSET)) >> 8) & 1;
		volatile int sw2_pushed = (*((volatile uint32_t *)(GPIOB_BASE_ADDR+GPIOB_IDR_OFFSET)) >> 10) & 1;

		if(sw1_pushed) //Blink LED
		{
			while(!sw2_pushed) // stop LED Blink when switch 2 is pressed
			{
				//Set LED
				*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) |= (0x1 << 10);
				//Delay
				for (volatile int count = 0 ; count < 100000 ; count++ );
				//Clear LED
				*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOA_ODR_OFFSET)) &=	~(0x1 << 10);
				for (volatile int count = 0 ; count < 100000 ; count++ );
				sw2_pushed = (*((volatile uint32_t *)(GPIOB_BASE_ADDR+GPIOB_IDR_OFFSET)) >> 10) & 1;
			}
		}

	}
}
