/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    17-5-2026
 *
 * Description:
 *   This file is the main entry point for an STM32F446RE embedded
 *   application that initializes the FPU, clocks, I2C, and UART
 *   peripherals, then continuously reads accelerometer and gyroscope
 *   data from an MPU6050 sensor over I2C and transmits the formatted
 *   results via UART. It also includes an unused `i2c_scan` utility
 *   function that probes the I2C bus for connected devices.
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446re.h"
#include "i2c.h"
#include "bmp280.h"
#include "mpu6050.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define NDATA 10

void init_clocks(void);

int main(void)
{
	// Enable FPU — must be done before any float operation
	*((volatile uint32_t *)0xE000ED88) |= ((3UL << 10*2) | (3UL << 11*2));
    init_clocks();
    init_i2c_gpio();
    i2c_init();
    init_uart();
//    uint8_t bmp280_addr = BMP280_ADDR_SDO_LOW;
    uint8_t mpu_addr 	= MPU6050_ADDR_ADO_LOW;
//    bmp280_i2c_init(bmp280_addr);
    mpu6050_init(mpu_addr);
    for(volatile int i = 0; i < 10000; i++);  // wake-up delay
    uart_send_string("Ready for Testing:\r\n");
    char output_str[50];
    mpu6050_data_t sensor_read;
	for(;;){
		uint8_t id[1];
		mpu6050_read_who_am_i(id);
		if (id[0] == 0x68){
			uart_send_string("MPU6050 OK: 0x68\r\n");
			mpu6050_read_data(mpu_addr, &sensor_read);
			sprintf(output_str, "a_x: %.2fg a_y: %.2fg a_z: %.2fg\r\n",
					(float)sensor_read.accel_x/16384, 	//2^15 / 2g (sensitivity)
					(float)sensor_read.accel_y/16384,
					(float)sensor_read.accel_z/16384);
			uart_send_string(output_str);
			sprintf(output_str, "g_x: %.2fd/s g_y: %.2fd/s g_z: %.2fd/s\r\n",
					(float)sensor_read.gyro_x/131, //2^15 / 250g (sensitivity)
					(float)sensor_read.gyro_y/131,
					(float)sensor_read.gyro_z/131);
			uart_send_string(output_str);
		} else {
			uart_send_string("MPU6050 FAIL\r\n");
		}
		for(volatile int i=0; i < 1000000 ; i++){}; // simple delay
	}
}
void init_clocks(void){
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)) 	|= 	(3u << 0);		//  Bit 0,1 for GPIOA/B
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|=  (1u << 17);		//Enable clock for USART
	*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET))	|= 	(1u << 21);		// Bit 21 for I2C1
}
void i2c_scan(void){
    for(uint8_t addr = 0x08; addr < 0x78; addr++){
        // Generate START
        I2C1_CR1 |= I2C_CR1_START;
        while(!(I2C1_SR1 & I2C_SR1_SB));

        // Send address
        I2C1_DR = (addr << 1 | 0);

        // Wait for ADDR (ACK) or AF (NACK)
        while(!(I2C1_SR1 & (I2C_SR1_ADDR | I2C_SR1_AF)));

        if(I2C1_SR1 & I2C_SR1_ADDR){
            // ACK — device found, clear ADDR
            (void)I2C1_SR1;
            (void)I2C1_SR2;
            uart_send_string("Device found at: 0x");
            uart_send_char("0123456789ABCDEF"[addr >> 4]);
            uart_send_char("0123456789ABCDEF"[addr & 0x0F]);
            uart_send_string("\r\n");
        } else {
            // NACK — clear AF
            I2C1_SR1 &= ~I2C_SR1_AF;
        }
        // Generate STOP
        I2C1_CR1 |= I2C_CR1_STOP;
        for(volatile int i = 0; i < 10000; i++);
    }
    uart_send_string("Scan complete.\r\n");
}
