/*
 * File:    main.c
 * Author:  Alexander130892
 * Date:    30-5-2026
 *
 * Description:
 *   This STM32F446RE microcontroller program initializes UART2 and
 *   UART4 interfaces, then enters an infinite loop that transmits
 *   characters ('A', 'B', 'C') over UART4 while monitoring a circular
 *   buffer from UART2 input and displaying received data. The program
 *   uses GPIO polling on pin PA1 as a control signal and includes
 *   software delays between operations.
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include 	<stdint.h>
#include 	"uart.h"
#include	"stm32f446re.h"
#include 	"timer.h"

extern char buffer[UART_MAX_LENGTH];
extern volatile uint8_t head ;
extern volatile uint8_t tail ;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uart2_gpio_init();
	uart2_init();
	uart4_gpio_init();
	uart4_init();
	//timer2_init();
    /* Loop forever */
	uart_send_char('T');
	uart2_transmit('\r');
	uart2_transmit('\n');
	for(volatile uint32_t delay = 0; delay < 100000; delay++);
	for(;;){
		if(head != tail) {
			uart2_transmit(buffer[tail]+0x30);
			uart2_transmit('\r');
			uart2_transmit('\n');
			tail = (tail + 1) % UART_MAX_LENGTH;
		}
		while((*((volatile uint32_t *)(GPIOA_BASE_ADDR + GPIOx_IDR_OFFSET)) & (1u << 1)) == 0);  // wait until PA1 idle
		uart4_transmit('A');
		for(volatile uint32_t delay = 0; delay < 50000; delay++); // processing delay
		uart4_transmit('B');
		for(volatile uint32_t delay = 0; delay < 50000; delay++); // processing delay
		uart4_transmit('C');
		for(volatile uint32_t delay = 0; delay < 50000; delay++);
		uart4_transmit('\n');
		for(volatile uint32_t delay = 0; delay < 100000; delay++);
	}
}

